An info page about a plugin for integrating Simple Analytics with WP
simpleanalytics/docs pull request #19
Opened 2023-05-10 10:41 UTC by ChrisPlaneta

I added it to the main menu. I don't know if you want to keep it like that or add an info in the existing page about WordPress plugins (like you did with that other WP plugin).

2023-05-11 11:12 UTC, adriaanvanrossum requested changes

2023-05-11 11:12 UTC, adriaanvanrossum commented on _docs/31_integrations/06_wordpress_wpfullpicture.md
> +* Join traffic data from multiple websites under one domain without the need to [modfy the script](https://docs.simpleanalytics.com/overwrite-domain-name)
Little typo :)

2023-05-11 11:13 UTC, adriaanvanrossum commented
Looks great! Thanks for your time, @ChrisPlaneta. Will publish after that little typo is fixed.

2023-05-11 12:40 UTC, ChrisPlaneta commented
Hi Adriaan

I will need your help here. I normally never use GitHub for my projects and
I actually have no idea what typo you are talking about :/ I read
documentation from GitHub and I am more lost then before. See the
attachment. This is what I see and I have no clue where this typo is
marked. Can you point me in the right direction here?

Thanks and have a nice day
Krzysztof

czw., 11 maj 2023 o 13:13 Adriaan ***@***.***> napisał(a):

> Looks great! Thanks for your time, @ChrisPlaneta
> <https://github.com/ChrisPlaneta>. Will publish after that little typo is
> fixed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/simpleanalytics/docs/pull/19#issuecomment-1543802918>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJIHDZXGUI76ZEBBXEUUALXFTCVVANCNFSM6AAAAAAX4RQMMI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-11 12:50 UTC, ChrisPlaneta commented
Oh. I think I have got it. However, I'm not sure if you can see the change. Let me know.

2023-05-29 08:37 UTC, adriaanvanrossum commented
Thanks Chris, will merge it. No worries about the typo, will fix if it's still there.

2023-05-29 08:37 UTC, merged